# Generated by Django 5.0.7 on 2024-08-25 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AlimentoPro', '0001_initial'),
        ('GanadoPro', '0001_initial'),
        ('Person', '0002_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_c', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Corral',
                'verbose_name_plural': 'Corrales',
            },
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Peso_alimentacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_alimentacion', models.DecimalField(decimal_places=20, max_digits=30)),
                ('id_compra_alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AlimentoPro.compraalimento')),
                ('is_activite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.estado')),
                ('id_corral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ControlAlimentacion.corral')),
            ],
            options={
                'verbose_name': 'Alimentacion',
                'verbose_name_plural': 'Alimentacions',
            },
        ),
        migrations.CreateModel(
            name='DetalleAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_alimentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ControlAlimentacion.alimentacion')),
            ],
            options={
                'verbose_name': 'Detalle Alimentacion',
                'verbose_name_plural': 'Detalles Alimentaciones',
            },
        ),
        migrations.CreateModel(
            name='GanadoCorral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=6)),
                ('cantidad', models.IntegerField()),
                ('id_corral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ControlAlimentacion.corral')),
            ],
            options={
                'verbose_name': 'Ganado Corral',
                'verbose_name_plural': 'Ganado Corral',
            },
        ),
        migrations.CreateModel(
            name='DetalleGanadoCorral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(max_length=250, null=True)),
                ('id_ganado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GanadoPro.ganado')),
                ('is_activite', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Person.estado')),
                ('id_corral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ControlAlimentacion.ganadocorral')),
            ],
            options={
                'verbose_name': 'Detalle Ganado Corral',
                'verbose_name_plural': 'Detalles Ganado Corral',
            },
        ),
    ]
