# Generated by Django 5.0.7 on 2024-08-25 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0002_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexoGanado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=15)),
                ('abreviatura', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ganado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('color', models.CharField(max_length=250)),
                ('marca', models.CharField(default='-', max_length=5)),
                ('is_activite', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Person.estado')),
                ('id_sexo_g', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GanadoPro.sexoganado')),
            ],
            options={
                'verbose_name': 'Ganado',
                'verbose_name_plural': 'Ganados',
            },
        ),
        migrations.CreateModel(
            name='GanadoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=5)),
                ('cantidad', models.IntegerField()),
                ('costo_total', models.DecimalField(decimal_places=20, max_digits=30)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.proveedor')),
            ],
            options={
                'verbose_name': 'Compra de Ganado',
                'verbose_name_plural': 'Compras de Ganado',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompraGanado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=20, max_digits=30)),
                ('id_ganado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GanadoPro.ganado')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GanadoPro.ganadocompra')),
            ],
            options={
                'verbose_name': 'Detalle Compra Ganado',
                'verbose_name_plural': 'Detalles Compra Ganado',
            },
        ),
    ]
