# Generated by Django 5.0.7 on 2024-07-28 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionDomiciliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('denominacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CondicionDomiciliaria',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'db_table': 'person_estado',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('denominacion', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('denominacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nacionalidad',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrigenEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('denominacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'OrigenEntidad',
            },
        ),
        migrations.CreateModel(
            name='TipoContribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('denominacion', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name': 'Tipo Contribuyente',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sunat', models.CharField(max_length=10)),
                ('denominacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Documento',
            },
        ),
        migrations.CreateModel(
            name='TipoVia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('deniminacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('denominacion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_condicionDomiciliaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.condiciondomiciliaria')),
                ('id_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Person.estado')),
                ('id_nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.nacionalidad')),
                ('id_tipo_contribuyente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Person.tipocontribuyente')),
                ('id_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.tipodocumento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.estado')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('id_origen_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.origenentidad')),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Person.persona')),
            ],
            options={
                'verbose_name': 'Persona Jurídica',
                'verbose_name_plural': 'Personas Jurídicas',
            },
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.genero')),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Person.persona')),
            ],
            options={
                'verbose_name': 'Persona Natural',
                'verbose_name_plural': 'Personas Naturales',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=150)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=150)),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_telefono', models.CharField(blank=True, choices=[('Movil', 'Móvil'), ('Fijo', 'Fijo'), ('Trabajo', 'Trabajo'), ('Casa', 'Casa'), ('Otro', 'Otro')], max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.estado')),
                ('id_operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.operador')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubigeo', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('bloque', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.departamento')),
                ('id_distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.distrito')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.estado')),
                ('id_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Person.persona')),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.provincia')),
                ('id_tipo_via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Person.tipovia')),
                ('id_tipo_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Person.tipozona')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
