# Generated by Django 5.0.7 on 2024-08-25 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.estado')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Person.persona')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
