# Generated by Django 5.0.7 on 2024-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='abreviatura',
            field=models.CharField(default='null', max_length=5),
            preserve_default=False,
        ),
    ]
