# Generated by Django 5.0.7 on 2024-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlimentoPro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraalimento',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
